#!/bin/sh

# Generate the molecular surface of the receptor
# This, rec.ms, has already been generated using program dms.

# Construct sphere set in active site
../../../dock6/bin/sphgen

# Select spheres within 10 Ang of ligand (Pick a sample ligand here)
../../../dock6/bin/sphere_selector rec.sph region.mol2 5.5

# Convert selected spheres into pdb format for viewing
../../../dock6/bin/showsphere < selected_spheres.in

# Convert spheres from largest cluster into pdb format for viewing
../../../dock6/bin/showsphere < sphgen_cluster.in
